// <auto-generated />
using System;
using DocMais.DATA;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DocMais.Migrations
{
    [DbContext(typeof(CLINICACONTEX))]
    [Migration("20260423164633_criaçãoInicial")]
    partial class criaçãoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DocMais.MODEL.MedicoModel", b =>
                {
                    b.Property<string>("crm")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("datanascimento")
                        .HasColumnType("longtext");

                    b.Property<string>("email")
                        .HasColumnType("longtext");

                    b.Property<string>("endereco")
                        .HasColumnType("longtext");

                    b.Property<string>("especialidade")
                        .HasColumnType("longtext");

                    b.Property<string>("nome")
                        .HasColumnType("longtext");

                    b.Property<string>("prioridade")
                        .HasColumnType("longtext");

                    b.Property<string>("telefone")
                        .HasColumnType("longtext");

                    b.HasKey("crm");

                    b.ToTable("medicos");
                });

            modelBuilder.Entity("DocMais.MODEL.PacienteModel", b =>
                {
                    b.Property<string>("cpf")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("datanascimento")
                        .HasColumnType("longtext");

                    b.Property<string>("email")
                        .HasColumnType("longtext");

                    b.Property<string>("nome")
                        .HasColumnType("longtext");

                    b.Property<string>("prioridade")
                        .HasColumnType("longtext");

                    b.Property<string>("telefone")
                        .HasColumnType("longtext");

                    b.HasKey("cpf");

                    b.ToTable("pacientes");
                });

            modelBuilder.Entity("DocMais.Model.AGENDAMENTOMODEL", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("cpfpaciente")
                        .HasColumnType("longtext");

                    b.Property<string>("crmmedico")
                        .HasColumnType("longtext");

                    b.Property<string>("dataatendimento")
                        .HasColumnType("longtext");

                    b.Property<string>("dataatendimentos")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("datahoraagendamento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("datanaciementopaciente")
                        .HasColumnType("longtext");

                    b.Property<string>("especialidademedico")
                        .HasColumnType("longtext");

                    b.Property<string>("horaatendimento")
                        .HasColumnType("longtext");

                    b.Property<string>("nomemedico")
                        .HasColumnType("longtext");

                    b.Property<string>("nomepaciente")
                        .HasColumnType("longtext");

                    b.Property<string>("paaciente")
                        .HasColumnType("longtext");

                    b.Property<string>("telefonepaciente")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("aGENDAMENto");
                });
#pragma warning restore 612, 618
        }
    }
}
